# Sample workflow
name: Mi Workflow

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# this workflow contains only a single job called 'build'
  build:
    runs-on: ubuntu-latest
    # Sequence os tasks that will be executed
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run:
          echo Add other actions to build,
          echo test, and deploy your project.
